/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED — DO NOT EDIT.
 * Run `npx convex dev` to regenerate.
 */

import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";
import type * as settings from "../settings.js";

type Mounts = {
  settings: typeof settings;
};

// Flatten the api.
export declare const fullApi: ApiFromModules<Mounts>;
export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
