/* eslint-disable */
/**
 * Generated data model types.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED — DO NOT EDIT.
 * Run `npx convex dev` to regenerate.
 */

import type { DataModelFromSchemaDefinition } from "convex/server";
import type schema from "../schema.js";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
export type TableNames = keyof DataModel;
export type Id<TableName extends TableNames = TableNames> = string & { __tableName: TableName };
