/* eslint-disable */
/**
 * Generated utilities for implementing server-side Convex query and mutation functions.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED — DO NOT EDIT.
 * Run `npx convex dev` to regenerate.
 */

export { query, mutation, action, internalQuery, internalMutation, internalAction } from "convex/server";
export type { QueryCtx, MutationCtx, ActionCtx } from "convex/server";
